openapi: 3.0.0

info:
  title: <APPLICATION NAME>
  description: <APPLICATION DESCRIPTION>
  version: <APPLICATION VERSION>
  x-products:
    - name: <PRODUCT NAME>
      product-id:
      description: <PRODUCT DESCRIPTION>
servers:
  - url: <APPLICATION SERVER ENDPOINT>

tags:
  - name: FrontPage
    description: Provides functionalities for web applications.
  - name: System
    description: Provides functionalities for operability of applications.

paths:
  /:
    get:
      security:
        - bearerAuth: []
      tags:
        - FrontPage
      summary: frontend
      description: Goes to login page of the application
      operationId: frontend
      responses:
        "200":
          description: Navigates to the page
        "404":
          description: Not found

  /heartbeat:
    get:
      security:
        - bearerAuth: []
      tags:
        - System
      summary: heartbeat
      description: To check if an application is alive
      operationId: heartbeat
      responses:
        "200":
          description: Success
        "404":
          description: Not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
